### ISSUE TITLE
Missing bis m/s conversion in HARPS.py

### ISSUE THREAD

**Issue by julia-mestre** [gomesdasilva/ACTIN2#3]
The bis is in km/s so it should also be included as a key in the km/s->m/s conversion in HARPS.py 
 
`keys = ['rv', 'berv', 'ccf_noise', 'fwhm', 'spec_rv', 'rv_wave_corr', 'bis']`

**Comment by gomesdasilva** [comment]
Thank you for pointing that out, it was missing also for HARPS-N. Both were corrected.
